#!/usr/bin/env python3
"""Generate main/util/geo_coords.c from tools/geo_coords_source.csv.

The CSV is Uwe DL8UG's own raw dataset (prefix,lat,lon,dxcc,iso3,name). He sent
it 2026-09-18 to replace the earlier ~4,100-prefix table:

    "There are regional peculiarities. In some cases, callsigns are distributed
     by region within a country. For example, China isn't just China... you can
     now resolve it even more finely by region based on the callsign, even
     though the DXCC is the same."

⛔ THE SOURCE CSV IS COMMITTED ALONGSIDE THIS SCRIPT, DELIBERATELY. The previous
table's own header pointed at a `tools/gen_geo_coords.py` that was never
committed and a source file that lived on one machine - so 4,100 hand-verified
rows were, in practice, unreproducible. A generated file whose generator is
missing is a hand-maintained file that nobody dares hand-maintain.

Encoding notes, all measured rather than assumed:

  * 18,356 of the 18,365 prefixes carry a coordinate that differs from what
    their parent prefix would give, so there is nothing to prune. The size IS
    the resolution; it cannot be had cheaper.
  * lat/lon are stored as int16 hundredths of a degree. Range fits (+-9000 /
    +-18000) and 0.01 deg is ~1.1 km - far finer than a country centroid and
    finer than the 70-150 km a Maidenhead square gives.
  * name/iso3/dxcc are deduplicated into a 340-entry entity table and indexed
    by uint16, because 18,365 copies of "European Russia" would cost more than
    the coordinates do.
  * The array is sorted by prefix and a first-character index is emitted, so a
    lookup scans one bucket (~500 rows) instead of all 18,365. The old table
    was a linear scan of 4,169; keeping that shape at 4x the size would have
    put the cost on every spot drawn.
"""
import csv, io, os, sys, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, "tools", "geo_coords_source.csv")
OUT  = os.path.join(ROOT, "main", "util", "geo_coords.c")

def main():
    rows = list(csv.DictReader(io.open(SRC, encoding="utf-8")))
    if not rows:
        sys.exit("gen_geo_coords: %s is empty" % SRC)

    ents, ent_idx = [], {}
    for r in rows:
        key = (r["name"], r["iso3"], r["dxcc"])
        if key not in ent_idx:
            ent_idx[key] = len(ents)
            ents.append(key)

    recs = []
    for r in rows:
        la = int(round(float(r["lat"]) * 100.0))
        lo = int(round(float(r["lon"]) * 100.0))
        assert -9000 <= la <= 9000 and -18000 <= lo <= 18000, r
        recs.append((r["prefix"].upper(), la, lo, ent_idx[(r["name"], r["iso3"], r["dxcc"])]))
    recs.sort(key=lambda x: x[0])

    # first-character buckets, so a lookup never scans the whole table
    firsts = sorted({p[0] for p, _, _, _ in recs})
    bucket = collections.OrderedDict()
    for i, (p, _, _, _) in enumerate(recs):
        bucket.setdefault(p[0], [i, i])[1] = i

    w = io.open(OUT, "w", encoding="utf-8", newline="\n")
    W = w.write
    W("// GENERATED BY tools/gen_geo_coords.py - DO NOT HAND-EDIT.\n")
    W("// Source: tools/geo_coords_source.csv (Uwe DL8UG, 2026-09-18).\n")
    W("// Re-run the script after replacing the CSV; both are committed so the\n")
    W("// table is reproducible, which the previous one was not.\n")
    W("//\n")
    W("// %d prefixes, %d entities. Coordinates are hundredths of a degree.\n" % (len(recs), len(ents)))
    W('#include "geo_coords.h"\n\n#include <string.h>\n#include <stddef.h>\n\n')
    W("typedef struct { const char *name; const char *iso3; uint16_t dxcc; } geo_entity_t;\n")
    W("static const geo_entity_t ENTITIES[] = {\n")
    for nm, iso, dx in ents:
        W('    {"%s", %s, %s},\n' % (nm.replace('"', '\\"'),
                                     ('"%s"' % iso) if iso else "NULL",
                                     dx if dx else "0"))
    W("};\n\n")
    W("typedef struct { const char *prefix; int16_t lat_c; int16_t lon_c; uint16_t ent; } prefix_coord_t;\n")
    W("static const prefix_coord_t PREFIX_COORDS[] = {\n")
    for p, la, lo, e in recs:
        W('    {"%s",%d,%d,%d},\n' % (p, la, lo, e))
    W("};\n")
    W("#define N_PREFIX_COORDS ((int)(sizeof(PREFIX_COORDS)/sizeof(PREFIX_COORDS[0])))\n\n")
    W("// First character -> [lo,hi] slice of PREFIX_COORDS, so a lookup scans one\n")
    W("// bucket instead of all %d rows.\n" % len(recs))
    W("typedef struct { char c; uint16_t lo, hi; } bucket_t;\n")
    W("static const bucket_t BUCKETS[] = {\n")
    for c in firsts:
        lo, hi = bucket[c]
        W("    {'%s',%d,%d},\n" % (c if c != "'" else "\'", lo, hi))
    W("};\n")
    W("#define N_BUCKETS ((int)(sizeof(BUCKETS)/sizeof(BUCKETS[0])))\n")
    w.close()
    print("gen_geo_coords: %d prefixes, %d entities -> %s" % (len(recs), len(ents), OUT))

if __name__ == "__main__":
    main()
